print("Welcome to the food store😎😎")
print("we sell any kind of food you wish")
print("our slogan is am cooler than andrew -eddie ")
print("our product are sandwich for 8$ hamburger for $12 french fries for $6 and coke for 13$ ")
print("Hope you have a nice time shopping at the food store")